query getMeasurements(
  $account: String!
  $startAt: DateTime!
  $endAt: DateTime!
  $utilityFilters: [UtilityFiltersInput!]
  $timezone: String
) {
  account(accountNumber: $account) {
    properties {
      id
      measurements(
        first: 1500
        utilityFilters: $utilityFilters
        startAt: $startAt
        endAt: $endAt
        timezone: $timezone
      ) {
        edges {
          node {
            value
            unit
            ... on IntervalMeasurementType {
              startAt
              endAt
            }
          }
        }
      }
    }
  }
}
